package kr.or.waterpark.common.enumpkg;

public enum ServiceResult {
	OK, FAIL, NOTEXIST, INVALIDPASSWORD, PKDUPLICATED, NOTENOUGH
	, DAYTICKET, MIXEDTICKET, YEARTICKET, NEEDONLYONE, NOTALLOWED, ALREADYHAVE, CANCELED
	, EXPIRED
}
